### ISSUE TITLE
paintTraverse error while building in debug but not in release also crashing on inject while in release

### ISSUE THREAD

**Issue by DemonLoverHvH** [Bartis1313/csgo#10]
![3b20ac91a8f7283ec49a36e2a459ec9f](https://user-images.githubusercontent.com/51270049/147777369-f442a64c-3672-4eb0-ac50-5188f4e78086.png)

**Comment by Bartis1313** [comment]
because debug LF is empty itself, it will obviously will fail there. Just do macros to check if it's under debug, if so do not use lazy importer. Fix will come tomorrow, as I have some small mess in gui classes right now.

**Comment by Bartis1313** [comment]
Ok, removed some mess I did in gui, you shouldn't get any errors when compiling in any version now.
If it crashes, then check what debug says for you. For debugging use any simple injection method that will allow you to actually debug anything.

**Comment by DemonLoverHvH** [comment]
> Ok, removed some mess I did in gui, you shouldn't get any errors when compiling in any version now. If it crashes, then check what debug says for you. For debugging use any simple injection method that will allow you to actually debug anything.

alright thanks ye the errors are gone im able to inject debug ver perfectly fine now still not able to inject with release mode and since its release im having a bit of a hard time debugging it cuz its not as straight forward
