### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by ExoniaToken** [Bartis1313/csgo#12]
![Screenshot_4](https://user-images.githubusercontent.com/95836002/148633545-984ed01e-d666-4b92-9d15-0c024a714b01.png)

**Comment by Bartis1313** [comment]
Just comment it, GUI will prolly be finished in 7 days or so

**Comment by ExoniaToken** [comment]
https://cdn.discordapp.com/attachments/929069498164711505/929740862844461116/unknown.png

**Comment by Bartis1313** [comment]
With that nobody ever will help you, check printed stack, check what failed and where and why.
By now I can only see that filesystem returned somewhere runtime error.

**Comment by ExoniaToken** [comment]
oh my bad fixed

**Comment by Bartis1313** [comment]
Can I know what exactly was the fix? It will help for other people too

**Comment by ExoniaToken** [comment]
i formatted pc and i installed c++ redistributables and fixed

**Comment by ExoniaToken** [comment]
its crashing when inject but with -insecure its not crashing why ?

**Comment by Bartis1313** [comment]
I doubt the flag to launch the game will cause the crash, it might be due to injector. I personally have never injected it on normal launch. Will inform you tomorrow or in few days.

**Comment by ExoniaToken** [comment]
okay

**Comment by Bartis1313** [comment]
I can't really find any reason, this flag is not a reason ever. Only what I can imagine is injector somehow blocking access to resource which can crash.
Solution: use any other injector, or compile it correctly.
