### ISSUE TITLE
How do i change the signitures/offsets (crashing on inject)

### ISSUE THREAD

**Issue by Nonsocial9** [Bartis1313/csgo#15]
Because its crashing on inject

**Comment by Bartis1313** [comment]
Because it's sometimes useful to debug to say sig was wrong or some offset (this source does not use very hardcoded offsets)
[#13](https://github.com/Bartis1313/csgo/issues/13)
[#12](https://github.com/Bartis1313/csgo/issues/12)

**Comment by Nonsocial9** [comment]
Hey Bratis , I stopped it from crashing by commenting out test::init(); in source.cpp but now when ever I inject it gives me this menu. I feel kinda retarded but i'd like some help as i have no idea sorry in advance.

**Comment by Bartis1313** [comment]
Menu is not finished, I left it like that to fix it in free time. 
This line returned error, because pointer to resource had to be null. Injector's fault.

**Comment by Nonsocial9** [comment]
ha

**Comment by Nonsocial9** [comment]
> Menu is not finished, I left it like that to fix it in free time. This line returned error, because pointer to resource had to be null. Injector's fault.

So your saying the menu isnt the image?

**Comment by Bartis1313** [comment]
Read the code.
I am finishing gui this week, for images this is an optional choice to anyone that will easy as it needs only one argument.
