### ISSUE TITLE
 injection

### ISSUE THREAD

**Issue by sakula6** [Bartis1313/csgo#16]
Crash during injection, expecting update

**Comment by DemonLoverHvH** [comment]
Release or Debug mode?

**Comment by EinsDreiDreiSiebenX** [comment]
Both

**Comment by DemonLoverHvH** [comment]
add a couple breakpoints and inject debug with vs attached

**Comment by sakula6** [comment]
Release mode, flash back after injection!

**Comment by EinsDreiDreiSiebenX** [comment]
> Contributor

Exception thrown at 0x774DB662 in csgo.exe: Microsoft C++ exception: std::filesystem::filesystem_error at location 0x4549F6AC.

Exception thrown at 0x458A0D30 in csgo.exe: 0xC00001A5: An invalid exception handler was found (parameter: 0x00000004).

**Comment by Bartis1313** [comment]
That just doesn't sound right. 
Same as [#5](https://github.com/Bartis1313/csgo/issues/5)

**Comment by DemonLoverHvH** [comment]
> That just doesn't sound right. Same as [#5](https://github.com/Bartis1313/csgo/issues/5)


ye works perfectly fine on my end

**Comment by froggisfriend** [comment]
Hack is updated, works perfectly fine for me.
