### ISSUE TITLE
Empty Menu

### ISSUE THREAD

**Issue by NicoletteShea** [Bartis1313/csgo#17]
Hey!
I can't understand, the cheat has menu functions, but when injected it shows an empty pink-gray menu, how can I bind functions or how can I make the menu that in the screenshot work? Someone please help me fix this, here is my discord for communication: GGBEST#0225
[https://pastenow.ru/2ecce654072dd189e9fdd9a675677e00](url) @Bartis1313

**Comment by Bartis1313** [comment]
wtf is this link and yes, it's because I had then just gui classes working. Now it's pseudo auto padded with pos to draw. Will push an update in hour or so

**Comment by NicoletteShea** [comment]
that is, in an hour the menu that you have in the screenshot will be the same?  I just don’t know how to solve the problem with the fact that the menu is different, when I downloaded the source I was shocked, there is a cheat function, but the menu is empty :)

**Comment by Bartis1313** [comment]
menu from screenshot is already in, if you read more code, you will be able to find it.
Note that this cheat is not finished and updated when I have free time.
The menu from ss is just: [line in hook](https://github.com/Bartis1313/csgo/blob/master/cheats/hooks/paintTraverse.cpp#L80)
So you comment the gui stuff and use this x88 style menu, which eventually in some time will be an option to select in runtime.

**Comment by NicoletteShea** [comment]
That is, at the moment, what menu is used?  I just didn’t have the opportunity to look, in fact you just made a hook, as I understand it, the x88 menu in the menu that is currently?

**Comment by Bartis1313** [comment]
No idea what are you talking about it, maybe translator has failed.
I gave you where the old menu was used, and all you have to do is uncomment it and comment current gui stuff.
If this is still not understandable, wait for my update which will give you the choice between menus.

Closing as it makes no sense to explain how to comment lines or uncomment.
