### ISSUE TITLE
just a tiny fix

### ISSUE THREAD

**Issue by kaposzta99** [Bartis1313/csgo#2]
its not 200 tick backtrack its 200 ms.

![ok](https://user-images.githubusercontent.com/63308528/140923686-908571d0-a20f-4715-8515-1b2d27a4fdc6.png)

**Comment by Bartis1313** [comment]
Yes, my mistake. Will be fixed today and also will try to add the ticks to edit in the backtrack.

**Comment by Bartis1313** [comment]
I fixed this small typo and commented ticks option in the backtrack for anyone who wants to use it/explore. Sorry for a bit late fix.
