### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Mr-zhao98** [Bartis1313/csgo#24]
![image](https://user-images.githubusercontent.com/61860970/157226902-923d9ede-d632-41a6-b356-1308e7e2f5ad.png)
我是新手  不知道什么原因

**Comment by Bartis1313** [comment]
and I am not from CH.

**Comment by Mr-zhao98** [comment]
I'm a novice.     About this error,  I don't know why.
Where are you from?
You are really good.

**Comment by Mr-zhao98** [comment]
I cloned it directly into vs.   Direct compilation run
I use the vs2022 version, and you use the vs2019 version. Is that the reason?

**Comment by Bartis1313** [comment]
maybe, I don't know. Did you select the sln file? It doesn't seem right

**Comment by Mr-zhao98** [comment]
![image](https://user-images.githubusercontent.com/61860970/157238717-44a66bee-d703-4c5d-a845-4c5057fb1cbb.png)
Is this the right choice? However, the prompt: "Debugging cannot be enabled"

**Comment by Bartis1313** [comment]
compile as debug - use it for debugging
compile as release - use it as optimized version
You seem to don't even know how to use your environment, I highly advise to not start any game hacking from this source.
Same goes for code.
To compile this, you should go for BUILD tab, not pressing this debug green mark.

**Comment by RXVAN** [comment]
> I cloned it directly into vs. Direct compilation run I use the vs2022 version, and you use the vs2019 version. Is that the reason?

You dont RUN the dll, you need to inject it using an injector. You can find many on github for example, just check them for hidden viruses :/

google translate: (sorry)
您不运行 dll，您需要使用注入器注入它。 例如，您可以在 github 上找到很多，只需检查它们是否有隐藏病毒 ：/

**Comment by Bartis1313** [comment]
@RXVAN thanks for further explanation for him/her.
I am closing this issue as I really don't think it's needed, people that struggle with doing something that takes one minute have zero experience, and want more and more.
Anyone here reading, this is now the reason those threads will be closed by me with no reply.
Give at least smallest impact. 
![image](https://user-images.githubusercontent.com/69613796/157314915-701723a5-3098-42e3-b8a0-27a0ebfa83aa.png)
