### ISSUE TITLE
Cannot open include file: 'format': No such file or directory

### ISSUE THREAD

**Issue by smokez129** [Bartis1313/csgo#25]
Cannot open include file: 'format': No such file or directory
how do i fix it i looked for a file named format but i cant find it

**Comment by Bartis1313** [comment]
This is a standard coming from c++20. You changed the version in project or you are missing those files.

**Comment by Bartis1313** [comment]
Coming back again to just add, your vs can be pretty old. Since vs 16.10 std::format is supported. In future the source will not only be limited for this environment.
Updating vs will probably remove your errors.

**Comment by smokez129** [comment]
Thanks i will try updating

**Comment by smokez129** [comment]
yes it works and the old menu design do you still have the code fore it?

**Comment by Bartis1313** [comment]
Old menu was rendered with surface at all. I deleted it becuase it used to annoy me everytime to add more handlers and the objects for elements were not dynamic, that used to lead for making callbacks, which I hated. Feel free to look old commits, but the code for it was not very worth to reback. Only what could be worth was surface colorpicker.
PS it's possible to reback such style by overwriting imgui widgets with your own style. If you know how, you can create pull request so other people will have a choice/example.

**Comment by smokez129** [comment]
i will try i know little more than the basics

**Comment by Bartis1313** [comment]
![image](https://user-images.githubusercontent.com/69613796/158685389-d5e1f2f4-a654-48b5-a71d-759d4c74fd49.png)
it works, you can play with other models for beams. Or even add effects, I plan to go more advanced for that.
