### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by cstatics** [Bartis1313/csgo#29]
The cheat actually Crashes if youre Using the legit bot 
After about the second enemy the aimbot locks  
It crashes

**Comment by cstatics** [comment]
But keep up the great work

**Comment by Bartis1313** [comment]
At the time of adding key class I had zero problems with that. Debug it and show printstack.

**Comment by cstatics** [comment]
I know it Sounds wierd But i dont know How:,)

**Comment by cstatics** [comment]
The Only guy that know that is my friend But hes on vacation

**Comment by Bartis1313** [comment]
It's easier than it sounds, set debug and then in the debugging tab you have option to attach to the proccess. After setting it inject the cheat and you should see the printed stack of that error.

**Comment by Bartis1313** [comment]
Or just google how to debug dll at runtime in vs. I guess you don't want to use other tools.

**Comment by cstatics** [comment]
I will try
Have you noticed that tp is not working?

**Comment by QvvvQ** [comment]
Are you sure you're using the latest version? Try re-downloading, all of the problems you described seem to be non-existent.

**Comment by Bartis1313** [comment]
Close if fixed

**Comment by cstatics** [comment]
Ausnahme ausgelöst bei 0x75A9B982 in csgo.exe: Microsoft C++-Ausnahme: std::out_of_range bei Speicherort 0x00D7DAB4.
i know youre not german but thats what the debug said

**Comment by Bartis1313** [comment]
I can't randomly know what is under this address, but from the reason something with arrays indexing. In what member/function it showed that?

**Comment by cstatics** [comment]
When I'm enabling the legit aimbot and shooting on targets it crashes  with that message in debug

**Comment by Bartis1313** [comment]
When you were debugging, it showed you the exact place where and which line. From hour I am writing, I will be in home in about 2-3 hours and will tell if I see anything that might be the reason of it.

**Comment by cstatics** [comment]
Yeah thank you I mean I can record you that what's happening

**Comment by cstatics** [comment]
i made an video how this happens
https://www.youtube.com/watch?v=Nl-KtPPGJEc
i know shitty aim

**Comment by Bartis1313** [comment]
happening only with legitbot?

**Comment by Bartis1313** [comment]
Backtrack problem. Not legitbot at all because indexes here will be always correct. Will fix in 10-20mins.
And in future use tools that give you more info than just loaded pdb. X32dbg is example, found the reason with it very quickly.

**Comment by Bartis1313** [comment]
if this still happens reopen the issue, if not - leave it.
