### ISSUE TITLE
config saving issue

### ISSUE THREAD

**Issue by cstatics** [Bartis1313/csgo#34]
when you want to save the weapon cham to generic it dont want to safe that 
instead of loading the cham into generic it goes back to flat
![image](https://user-images.githubusercontent.com/76153338/170844829-46d09a79-d05f-4f77-8eda-52cffa99e15a.png)

**Comment by Bartis1313** [comment]
First, now you gotta delete all configs.

```c++
CONFIG_ADD_VARIABLE(int, iChamsWeapons, 0, "chams mode Weapons");
```
line 54 - correct
```c++
CONFIG_ADD_VARIABLE(int, iChamsArms, 0, "chams mode Weapons");
```
line 59 - paths to 54.
I probably didn't see it when copying previous names, to fix just use logically "Arms" in str.
Ideally to assert errors like that I can use imgui-like detection of strings with ids to prevent it in future.
Commit might be delayed, I am very busy right now.

**Comment by Bartis1313** [comment]
Closing last commit fixed it. Safety with ids will come later
