### ISSUE TITLE
Using TAB to change the values crash the game…

### ISSUE THREAD

**Issue by Rrhyast** [Bartis1313/csgo#36]

**Comment by Bartis1313** [comment]
it might be imgui related, is it going in infinite loop? Then it is.
If you are able, change imgui to some older version before low level backend function in wndproc. 
I don't use any custom changed stuff in imgui so it will be easy.
I will check it myself in few hours or days

**Comment by Rrhyast** [comment]
> it might be imgui related, is it going in infinite loop? Then it is. If you are able, change imgui to some older version before low level backend function in wndproc. I don't use any custom changed stuff in imgui so it will be easy. I will check it myself in few hours or days

I don't think it's infinite loop, it's just crash the game when u press TAB on the functions that editable with it.

**Comment by Bartis1313** [comment]
after digging, simple change without any code edit is to use ``IMGUI_DISABLE_WIN32_DEFAULT_IME_FUNCTIONS`` macro.
Will get rid of those backend issues and doesn't affect menu in any way.
Or to use imgui's branch without new backend logic.

**Comment by Bartis1313** [comment]
fixed
[macro to fix](https://github.com/Bartis1313/csgo/commit/fc84ff86a3456bba4876e6fd85ed4b0438f021dc#diff-444cab591cb850fd57939398e131a22889cf286e347d82e524753ab2b50c9c4eR12)
Closing...
