### ISSUE TITLE
createmove stutter fix

### ISSUE THREAD

**Issue by kaposzta99** [Bartis1313/csgo#4]
since 2020 june createmove hook causes stuttering when returning false. so you should set your local viewangles to the cmd viewangles in order to fix this issue.

code:
`

	bool __stdcall hooks::createMove::hooked(float inputFrame, CUserCmd* cmd)
    {	
	original(inputFrame, cmd);

	if (!cmd || !cmd->m_commandNumber)
		return false;

	game::localPlayer = reinterpret_cast<Player_t*>(interfaces::entList->getClientEntity(interfaces::engine->getLocalPlayer()));

	if (original(inputFrame, cmd))
		interfaces::prediction->setLocalViewangles(cmd->m_viewangles);

`

**Comment by Bartis1313** [comment]
Right, forgive my laziness and literally not going through state of run command/prediction based stuff for reversal part.
Also next time if you can, create pull request for fix.

**Comment by kaposzta99** [comment]
okay, i don't really use github so i don't know how to make a pr but im gonna try next time xD
