### ISSUE TITLE
In game barrel

### ISSUE THREAD

**Issue by rrhyast** [Bartis1313/csgo#40]
Have you ever seen observer view angle line that polished very well? that's what i'm talking about.

**Comment by rrhyast** [comment]
> What feature are you referring to? Freelook? Freecam? Thirdpos? Those achieve vectors by not smoothing them (just directly setting them instantly), if this is a really needed case I can implement it, this is not very hard, the logic behind this takes couple of minutes.
> 
> If you refer to game's observer then not, I haven't digged into this at all.

I tbink this short video help you what i mean:
https://youtube.com/shorts/Zg_8URly6yU?feature=share

**Comment by Bartis1313** [comment]
This is obviously not my software.
I implemented this months ago, and till this day it works as intended.
![image](https://user-images.githubusercontent.com/69613796/181131344-cd0a1e16-344e-45ac-8409-ac0b74d04298.png)

**Comment by rrhyast** [comment]
> This is obviously not my software. I implemented this months ago, and till this day it works as intended. ![image](https://user-images.githubusercontent.com/69613796/181131344-cd0a1e16-344e-45ac-8409-ac0b74d04298.png) [See](https://github.com/Bartis1313/csgo/blob/master/cheats/features/visuals/player.cpp#L349)

yeah I see but it still need some tweaks, thanks anyway.
