### ISSUE TITLE
Changing thirdperson horizontal & vertical height

### ISSUE THREAD

**Issue by rrhyast** [Bartis1313/csgo#41]

**Comment by Bartis1313** [comment]
I don't see sense in changing those two fields at all, especially on 3rd cam.
I will add it anyway...

**Comment by rrhyast** [comment]
> I don't see sense in changing those two fields at all, especially on 3rd cam. I will add it anyway...

Its actually good for making thumbnails for videos to put cheat menu next to the player model.

**Comment by Bartis1313** [comment]
My menu is nothing but raw imgui, nothing really to show.
Anyway I will push it in some mins
pseudo: ``input->camera.x += config.thirdpersonX``
it's better to use freecam for such "images", but now I have a small problem with rendering local player in it.
Probably up to third person check, will check it later.

**Comment by rrhyast** [comment]
> My menu is nothing but raw imgui, nothing really to show. Anyway I will push it in some mins pseudo: `input->camera.x += config.thirdpersonX` it's better to use freecam for such "images", but now I have a small problem with rendering local player in it. Probably up to third person check, will check it later.

thanks!
