### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rrhyast** [Bartis1313/csgo#42]
why the nade helper circle were removed? it was really useful.

**Comment by Bartis1313** [comment]
It is [commented](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/visuals/world/nadepred.cpp#L204) you can also: [draw sphere](https://github.com/Bartis1313/csgo/blob/master/utilities/renderer/renderer.hpp#L382), [call some particle](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/particle/particle.hpp#L18), [call some effect](https://github.com/Bartis1313/csgo/blob/master/SDK/interfaces/interfaces.hpp#L97). Edit for your needs.

And public lists:
[Particles](https://developer.valvesoftware.com/wiki/List_of_CS:GO_Particles)
[Effects](https://developer.valvesoftware.com/wiki/List_of_Client_Effects)

**Comment by rrhyast** [comment]
> It is [commented](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/visuals/world/nadepred.cpp#L204) you can also: [draw sphere](https://github.com/Bartis1313/csgo/blob/master/utilities/renderer/renderer.hpp#L382), [call some particle](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/particle/particle.hpp#L18), [call some effect](https://github.com/Bartis1313/csgo/blob/master/SDK/interfaces/interfaces.hpp#L97). Edit for your needs.
> 
> And public lists: [Particles](https://developer.valvesoftware.com/wiki/List_of_CS:GO_Particles) [Effects](https://developer.valvesoftware.com/wiki/List_of_Client_Effects)

thanks!
