### ISSUE TITLE
Can u add onentitycreated and deleteentity to cheat

### ISSUE THREAD

**Issue by mp3096** [Bartis1313/csgo#44]
class IClientEntityListener
{
public:
	virtual void OnEntityCreated( C_BaseEntity* pEntity ) {}
	virtual void OnEntityDeleted( C_BaseEntity* pEntity ) {}
};
 
class CClientEntityList
{
public:
	virtual ~CClientEntityList() {}
 
	void AddListenerEntity( IClientEntityListener* pListener )
	{
		m_entityListeners.AddToTail( pListener );
	}
 
	void RemoveListenerEntity( IClientEntityListener* pListener )
	{
		m_entityListeners.FindAndRemove( pListener );
	}
 
private:
	CUtlVector<IClientEntityListener*> m_entityListeners;
};
 
//
class CClientEntityListener : public IClientEntityListener
{
	void OnEntityCreated( C_BaseEntity* pEntity ) override
	{
		// use pEntity
	}
 
	void OnEntityDeleted( C_BaseEntity* pEntity ) override
	{
		// use pEntity
	}
};
m_Listener = new CClientEntityListener();
entitylist->AddListenerEntity( m_Listener );
 
//
entitylist->RemoveListenerEntity( m_Listener );
delete m_Listener;
this is partial code u might find whole code somewhere
Thank you.

**Comment by Bartis1313** [comment]
Any explanation of why would it by helpful in my code?
Also, following the code you have one global listener field which is on heap for no reason, and to recreate you probably reallocate this filed. This is not what do you want to store on the heap at all.

This addon makes no sense, you can [see](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/events/events.cpp) how easily it is in source to deal with events handled by yourself, comments will help you.
I ignored part that this particular part of code does not apply to this source at all.

**Comment by mp3096** [comment]
Thanks for quick response the code I posted above was from difference source https://gitlab.com/counterstrikesource/ze-elite/-/blob/master/Project/ClientEntityListener.h

I was trying to port css feature to this cheat (auto laser )but couldn’t find those 2 (on create and delete)that’s why I was curious. I will tinker with it Events . Thanks for help

**Comment by Bartis1313** [comment]
You shouldn't rely on people's code, but rely on valve's public or leaked SDKs.
Events are [here](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events), and any cheat will use them in the same way. Maybe some people want to hook vfunc themselves and listen events like that, which doesn't work well for some events.
Anyway, for example you can take a look at: [hitmarker](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/visuals/hitmarker/hitmark.cpp#L109), [bullet tracer](https://github.com/Bartis1313/csgo/blob/master/cheats/features/sources/visuals/tracer/tracer.cpp#L30-L45).
I also have no idea what "auto laser" is.

**Comment by mp3096** [comment]
You have discord I can add u in? Btw here is demo of auto laser https://youtu.be/NF174hOwDOc
Basically there is boss entity which spawns laser either u crouch/jump to avoid them else die simple that was feature for css I was trying to implement for csgo

**Comment by Bartis1313** [comment]
I don't think this is what most people want, this is more like a personal request.
There are several ways how to achieve it. My logic would be:
1. Get the latest laser entity.
2. Get your current position
3. Get the laser position with width
4. Now you can use tracing or calculate it by yourself if width is "touching" your player model. By calculating delta in positions you can easily test when to jump or crouch. And delay must be related to the boss ent velocity speed, you don't want to crouch/jump all the time. Stop is basically when boss entity is behind you (use dot product or W2S to detect it)
5. Profit

**Comment by mp3096** [comment]
Thanks for help by any chance can u add me in discord if possible - flick7k#7284
You can close this.

**Comment by Bartis1313** [comment]
Sorry for bumping.
For reader: use cache entity system provided in the cheat, add own types if needed
