### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by Onyx123456** [Bartis1313/csgo#46]
>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1094,5): error MSB6006: "link.exe" exited with code 1104.
1>LINK : fatal error LNK1104: cannot open file 'freetype.lib'
1>Done building project "csgo-legit.vcxproj" -- FAILED.

**Comment by Bartis1313** [comment]
Try now, forgot to add to source control after paths had changed.
