### ISSUE TITLE
fatal error when joining game

### ISSUE THREAD

**Issue by unniggable** [Bartis1313/csgo#48]
![image](https://user-images.githubusercontent.com/27593195/194940708-d99545f8-125a-4fb3-bfa5-916813b86520.png)

i get this error when joining a game, but if i go into a game (without cheats) and then inject it works

**Comment by Bartis1313** [comment]
Will recheck what could possibly do it, did you have any stack walk printed in logs?
Paste that part too.

**Comment by Bartis1313** [comment]
And does that happen to your release build every single time?
If yes, then easier, if not then harder.

**Comment by unniggable** [comment]
> 

Yes happens every time with release. I get "Exception thrown at 0x3F21DCC5 (csgo-legit.dll) in csgo.exe: 0xC0000005: Access violation reading location 0xC762C80D." when im using the debugger

**Comment by unniggable** [comment]
Counter-Strike: Global Offensive
Map: de_mirage
Players: 1 (0 bots) / 10 humans
Build: 8598
Server Number: 1

No pure server whitelist. sv_pure = 0
The thread 0x2558 has exited with code 0 (0x0).
'csgo.exe' (Win32): Unloaded 'D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'
The thread 0x8a4 has exited with code 0 (0x0).
'csgo.exe' (Win32): Loaded 'D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'. 
'csgo.exe' (Win32): Unloaded 'D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'
'csgo.exe' (Win32): Loaded 'D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'. 
Error reading file resource/overviews/de_mirage_radar_spectate.dds.
PutClientInServer: no info_player_start on level
m connected.
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_INGAME
Exception thrown at 0x45BCDCC5 (csgo-legit.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x873C883C.

**Comment by Bartis1313** [comment]
Weird error, also hard to debug. I changed compiling option rules for frame pointers and seems like it doesn't throw it anymore.
I have also removed that exception pointer thingy, it sometimes could throw errors not related with the source at all.
Check newest commit, should fix?

**Comment by unniggable** [comment]
seems to be fixed now, thank you
