### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by Utkukck11** [Bartis1313/csgo#49]
![Screenshot (93)](https://user-images.githubusercontent.com/61580513/196792338-57c1da4c-97f2-4e03-9974-583fd8f22391.png)
im using csghost 2.4
`'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo.exe'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\apphelp.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AcGenral.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\samcli.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\userenv.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\urlmon.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winspool.drv'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mpr.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iertutil.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\SHCore.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\srvcli.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\netutils.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\GameOverlayRenderer.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\psapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\launcher.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wsock32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\steam_api.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\tier0.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vstdlib.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\umpdc.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\filesystem_stdio.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\engine.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wininet.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\steamnetworkingsockets.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\phonon.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\inputsystem.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vphysics.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\materialsystem.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\datacache.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\studiorender.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\soundemittersystem.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vscript.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\soundsystem.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\valve_avi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avifil32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvfw32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\comctl32.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vguimatsurface.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vgui2.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\panoramauiclient.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\v8.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\video.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libavcodec-56.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libavformat-56.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libavresample-2.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\v8_libbase.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\icui18n.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libavutil-54.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libswscale-3.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dbghelp.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\icuuc.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\panorama.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\cairo.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\v8_libplatform.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\parsifal.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\shaderapidx9.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\d3d9.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wldp.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\imemanager.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\localize.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\panorama_text_pango.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libfontconfig-1.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libglib-2.0-0.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libgobject-2.0-0.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libfreetype-6.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libpangoft2-1.0-0.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libpango-1.0-0.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\libgmodule-2.0-0.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\usp10.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamclient.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imagehlp.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\tier0_s.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\vstdlib_s.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mswsock.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\secur32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\crashhandler.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\stdshader_dbg.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\stdshader_dx9.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wdmaud.drv'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ksuser.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\avrt.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msacm32.drv'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\midimap.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\XInput1_4.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\InputHost.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMessaging.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\propsys.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreUIComponents.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dinput.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\hid.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wbem\wbemprox.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wbemcomn.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wbem\wbemsvc.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wbem\fastprox.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\amsi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\NapiNSP.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\pnrpnsp.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wshbth.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nlaapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dnsapi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nsi.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winrnr.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\FWPUCLNT.DLL'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\TextInputFramework.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\u0378390.inf_amd64_294c61aacdf3d58d\B382613\aticfx32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\u0378390.inf_amd64_294c61aacdf3d58d\B382613\atiu9pag.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\u0378390.inf_amd64_294c61aacdf3d58d\B382613\atiumdag.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dbgcore.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\u0378390.inf_amd64_294c61aacdf3d58d\B382613\atiumdva.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\amdihk32.dll'. Module was built without symbols.
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DXCore.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\igdumdim32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\igdusc32.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.UI.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WindowManagementAPI.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\twinapi.appcore.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\bin\matchmaking.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\bin\client.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\bin\server.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\scenefilecache.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shfolder.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_miles.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\mss32.dll'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\mssmp3.asi'. 
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\mssds3d.flt'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\XAudio2_7.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ResourcePolicyClient.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Users\Administrator\AppData\Local\Discord\app-1.0.9006\modules\discord_hook-1\discord_hook\d88e7fbd607\DiscordHook.dll'. 
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'. 
The thread 0x628 has exited with code 0 (0x0).
**** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#Panorama_CSGO_Spray_Cursor_Hint' on panel 'RosettaInfoText'
The thread 0x784 has exited with code 0 (0x0).
The thread 0x2440 has exited with code 0 (0x0).
**** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'PopupManager'
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Can't use cheat cvar cl_teamid_overhead_maxdist in multiplayer, unless the server has sv_cheats set to 1.
Unknown command "mat_antialias"
Unknown command "r_rootlod"
Unknown command "mat_picmip"
Unknown command "mat_reducefillrate"
Can't use cheat cvar mat_colorcorrection in multiplayer, unless the server has sv_cheats set to 1.
Unknown command "r_waterforcereflectentities"
Unknown command "mat_foreaniso"
NET_CloseAllSockets
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dhcpcsvc.dll'. 
Certificate expires in 44h49m at 1666370950 (current time 1666209607), will renew in 42h49m
Got SDR network config.  Loaded revision 406 OK
Performing ping measurement
SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
AuthStatus (steamid:76561199242419290):  OK  (OK)
Unknown command "cl_thirdperson"
Unknown command "tr_best_course_time"
Unknown command "tr_completed_training"
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'. 
'csgo.exe' (Win32): Unloaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\vaudio_celt.dll'. 
Unknown command "weapon_accuracy_logging"
Resource materials\panorama\images\icons\ui\globe.svg failed to load.
[02:42:01.969][PID 8696] PresentHandler(D3D9) created
[02:42:01.996][PID 8696] HookReset: hooked reset and reset_ex
[02:42:01.997][PID 8696] D3D9State::InitOverlay: initialized to 18D121A0 (window 00130D20: 1366x768)
Telling Steam it is safe to update the app
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\serverbrowser.dll'. 
'csgo.exe' (Win32): Unloaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\serverbrowser.dll'
'csgo.exe' (Win32): Loaded 'D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin\serverbrowser.dll'. 
Host_WriteConfiguration: Wrote cfg/config.cfg
DispatchAsyncEvent backlog, failed to dispatch all this frame. 246 of 259 remaining
--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_default
Ping measurement completed
Ping location: fra=79+7,vie=79+7/80+7,ams=105+10/84+7,par=100+10/88+7,waw=87+8/88+8,lhr=160+16/92+7,sto=117+11/99+7,sto2=117+11/99+7,mad=107+10/109+7,iad=211+21/165+7,gru=273+27/274+27,sgp=310+31/287+23
SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
--- Missing Vgui material vgui/../vgui/icon_con_medium.vmt
--- Missing Vgui material vgui/../vgui/icon_con_low.vmt
ChangeGameUIState: CSGO_GAME_UI_STATE_INTROMOVIE -> CSGO_GAME_UI_STATE_MAINMENU
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profapi.dll'. 
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "eom-winner"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-mainmenu-mission-card-bg"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-op-mainmenu-top"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-tournament-pass-status"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-op-mainmenu-rewards"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-op-mainmenu-missions"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-activemission-tooltip"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-active-mission"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
'csgo.exe' (Win32): Loaded 'C:\Users\Administrator\Downloads\csgo-legit.dll'. Module was built without symbols.
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\D3DX9_43.dll'. 
'csgo.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\D3DX9_43.dll'
'csgo.exe' (Win32): Loaded 'C:\Windows\SysWOW64\D3DX9_43.dll'. 
The thread 0x4a0 has exited with code 2032861184 (0x792b0000).
Exception thrown at 0x792DBE1D (csgo-legit.dll) in csgo.exe: 0xC0000005: Access violation reading location 0xAB8409CA.

The program '[8696] csgo.exe' has exited with code 0 (0x0).`

**Comment by Bartis1313** [comment]
Debugging with manual map will not help you at all. I am not the author of any of those injectors.
For "downloadable" injector, use any with loadlib. Or make your own where you handle all of exceptions correctly.

**Comment by Bartis1313** [comment]
Anyway, for you I have downloaded this injector in the newest release, and it is working.
Side note: don't think such ways of disabling vac will help you, since this is public it's only a source for them to learn.

**Comment by Utkukck11** [comment]
Yeah ik Vac updated and the antivac on the 2.4 version not work im using it bcs i love the CMD injector i will try an load library injector thanks.

**Comment by Utkukck11** [comment]
![Screenshot (94)](https://user-images.githubusercontent.com/61580513/196926402-16879a80-e7ee-4bd3-a582-52ab425e1df9.png)
load library injector doesnt worked too

**Comment by Utkukck11** [comment]
im using -insecure

**Comment by Utkukck11** [comment]
![Screenshot (95)](https://user-images.githubusercontent.com/61580513/196927387-a02b9f5b-05f5-4d5c-9f34-f2e19673aa8f.png)
with extreme injector

**Comment by Bartis1313** [comment]
release debugging also doesn't help you

**Comment by Utkukck11** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/61580513/196943366-d666d6a0-6afa-4e54-ba1e-0696097eaa6f.png)

**Comment by Bartis1313** [comment]
The problem is that probably this isn't the right place to call it or too soon. Go to [mirrorcam](https://github.com/Bartis1313/csgo/blob/master/cheats/features/visuals/mirrorcam/mirrorCam.cpp#L21)
And do this
```c++
//interfaces::matSys->forceBeginRenderTargetAllocation();
m_texture = interfaces::matSys->createFullFrameRenderTarget(XOR("mirrorCam"));
//interfaces::matSys->forceEndRenderTargetAllocation();
```
I have no time to debug it now, in 2h I will be free, it probably just calls it too soon

**Comment by Utkukck11** [comment]
worked thanks
