### ISSUE TITLE
crash on inject

### ISSUE THREAD

**Issue by tatutarko** [Bartis1313/csgo#5]
everytime i try to inject the game crashes 
methods I use:  manualmap, loadlibraryA

**Comment by tatutarko** [comment]
yea i compile on x64 and x86
csghost v4 and extreme injector
visual studio v142 and v141 
w11

**Comment by Bartis1313** [comment]
Compile only with x86, inline asm code would not be allowed for x64 or even registers used in vectored exception handler, and game itself is x86. Don't go from v142 to v141, it won't help anyhow.
Those injectors should not be a problem.
**Before that verify game files once again and attach debugger before injection with debug version for dll, provide what it says.**

**Comment by tatutarko** [comment]
I forgot to debug yes when the debug process started I got the error wkernalbase.pdb not loaded and i fix it
then i got this error :
Unhandled exception at 0x3F4CE9FD in csgo.exe: 0xC00001A5: An invalid exception handler routine has been detected (parameters: 0x00000004).

**Comment by Bartis1313** [comment]
Show printed stack, it's something either to injector or the hook gets not called correctly.
It might be also up to the OS itself, unfortunately I use windows 10.
In short time I will install windows 11 on vm and see what is really going on if system related.

**Comment by Bartis1313** [comment]
Okay I have fixed it, this has nothing to do with system (was stupid idea to say that).
If problem still occurs the issue must be on your side. I can only help when you show the full debug information.
How to see the debug information should be pretty easy, just post full screen if possible.

**Comment by tatutarko** [comment]
I'm using windows 10 now but I'm facing the same error again
![image](https://user-images.githubusercontent.com/94367007/142206462-ccac871f-c190-47e4-a0a9-4503f8d01c17.png)

**Comment by Bartis1313** [comment]
do not debug with manual map

**Comment by tatutarko** [comment]
![image](https://user-images.githubusercontent.com/94367007/142241666-018d6ee8-8a1b-4676-8902-536f733bf824.png)
my bad sorry

**Comment by Bartis1313** [comment]
ok then it somewhat did not detect your documents dir. I will recheck it.

**Comment by Bartis1313** [comment]
I have checked once again, it seems it did not created folder for you? If this path exists that debug has printed (__DOCUMENTS), the issue must be only up to system blocking you rights to create a folder.  Check if line 31 in this file ever returns the true.
Lazy fix for now as I can't really detect it, is to make folder yourself. I will push the repo in a moment with handling this error properly so you get the info.

**Comment by tatutarko** [comment]
i create a folder on documents but still same error
![image](https://user-images.githubusercontent.com/94367007/142268317-bfbb07c8-79c0-4618-9d50-63b5c19fe18d.png)

**Comment by Bartis1313** [comment]
ok pushed another update, to only see what the error says, this is a special case because prepareDirectories uses exactly same technique to obtain the folder, and it did work well. I might be blind, but I can't see the reasoning.
Fastest for you is to contact me directly, so I can help faster: Bartis#3611

**Comment by Bartis1313** [comment]
Closing the issue as problem is about missing system files or not installed system files.

**Comment by EinsDreiDreiSiebenX** [comment]
> Closing the issue as problem is about missing system files or not installed system files.

Which files are missing now?
