### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by JoshyJoshyJoshy** [Bartis1313/csgo#51]
can we have a built version? i dont have the storage for vcs

**Comment by JoshyJoshyJoshy** [comment]
Can we have the dll added into a release

**Comment by Bartis1313** [comment]
Compiling isn't heavy, it's not like it creates heavy files. And it's even worse idea, may lead to many ub's which are on user side, not the code.

**Comment by JoshyJoshyJoshy** [comment]
No it's visual code studio. It takes up like 7gb

**Comment by Bartis1313** [comment]
It's still light, are you on storage like 128GB?

**Comment by JoshyJoshyJoshy** [comment]
yes

**Comment by Bartis1313** [comment]
Closing as I really see no need for something like that, public files being shared around can be so easily blacklisted, has been known method what ac do, since punkbuster times or before. If you expect this to be fully undetected, then not really.
