### ISSUE TITLE
KeyValues Crash

### ISSUE THREAD

**Issue by gr1ndy** [Bartis1313/csgo#52]
https://pastebin.com/Zt9jFaKs

![image](https://user-images.githubusercontent.com/71841362/208150760-657d6839-4f96-4ca6-8c83-99465e2fc70e.png)

I updated the keyvalues sig cuz it was giving error during debug and now i get this error after last console log ( console logs are on the pastebin link ).

what could be the reason?

**Comment by Bartis1313** [comment]
Expect update today

**Comment by gr1ndy** [comment]
> Expect update today

alrighty

**Comment by Bartis1313** [comment]
code might be left with many many places touched and not finished, lots of added, lots of still need to refactor

**Comment by Bartis1313** [comment]
if you still encounter crashes, message again, when I wake up I will go lookup

**Comment by gr1ndy** [comment]
> if you still encounter crashes, message again, when I wake up I will go lookup

![image](https://user-images.githubusercontent.com/71841362/208296290-022ad94d-0483-4d26-bc28-bc94cebe4e00.png)

**Comment by Bartis1313** [comment]
no, if you debug it you will see that the key was not found because I added new config var. Delete the default config file and retry

**Comment by gr1ndy** [comment]
> no, if you debug it you will see that the key was not found because I added new config var. Delete the default config file and retry

oh ok

**Comment by gr1ndy** [comment]
ok so i found out that glow chams crashes.

**Comment by Bartis1313** [comment]
Yes, I did oopsie with hash map. Will update in few mins, thanks for reporting it
