### ISSUE TITLE
Minor issue in prediction

### ISSUE THREAD

**Issue by codecheck01** [Bartis1313/csgo#54]
https://github.com/Bartis1313/csgo/blob/ebad79b9d6525141526c93474c0764ee48503bf5/cheats/features/prediction/prediction.cpp#L72

Should be `m_afButtonReleased()` instead.

**Comment by Bartis1313** [comment]
thanks, will fix today

**Comment by Bartis1313** [comment]
yes it's correct (yours), while mine not.
Fastest way I did it is to lookup ``Prediction errors occurred`` string, which is a reference to leaked sdk
Here to get this var understood correctly, without var renames
```
if ( *(_DWORD *)(v7 + v3 + 36) && (*(int (__thiscall **)(int *))(dword_1523F5C8 + 52))(&dword_1523F5C8) )
        Warning("Prediction errors occurred at %i %f\n", *(_DWORD *)(off_10DAA8D0 + 28), *(float *)(off_10DAA8D0 + 16));
      v5 = a2;
    }
    v8 = v43 == -1;
    v6 = v43++ + 1;
  }
  while ( v8 );
  v35 = *(_BYTE *)(v3 + 9);
  if ( (*(unsigned __int8 (__thiscall **)(int *))(dword_14DFAA48 + 84))(&dword_14DFAA48) != v35 )
  ```
  Take a look at this:  ``` v35 = *(_BYTE *)(v3 + 9);```
  and an operation below which is literally [in sdk](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/client/prediction.cpp#L574)
Another ways would be to lookup ``cl_predict``, but I think it will be leading to same time in getting it, or even slower.
```
.text:10022AEF 68 E4 AB BB 10                          push    offset aClPredict ; "cl_predict"
.text:10022AF4 B9 48 AA DF 14                          mov     ecx, offset dword_14DFAA48
```
Will update it also, thanks again!

**Comment by Bartis1313** [comment]
Idk, seems useless as server overwrites compressed values, can't do anything about it. This is why I don't use those fields at all.
split will not.
To fix, you can do some compression removal yourself, but I don't know how would you do that.

**Comment by Bartis1313** [comment]
compression removal yourself - probably would end up fixing it as custom networked fields, not sure at all about that. This might break some of the error detections though. So I don't rush with doing it, current code is just what would you take from last leaked source and do it (in most).
