### ISSUE TITLE
it seem does not work

### ISSUE THREAD

**Issue by Koileo** [Bartis1313/csgo#55]
我已经编译好了dll，并且注入 csgo.exe ,但是csgo画面没有任何显示，不管我是否按下 “Home” “Insert” 
我想知道是我的DLL注入方式有问题是吗？
还是必须有其他的设置

**Comment by Bartis1313** [comment]
ok

**Comment by Koileo** [comment]
https://anonfiles.com/Rf40E3O4ye/csgo-legit_dll
这是我编译好的DLL文件

**Comment by Bartis1313** [comment]
I am not from China, and why would I need it this file?
Many times it's up to ABI and how your injector forces specific rules to it, as example exceptions.
Please use loadlibrary standard call for test and later code your own injector to prevent issues in future.

**Comment by Koileo** [comment]
Thanks，bro

**Comment by Bartis1313** [comment]
inactivity
