### ISSUE TITLE
Only works with -insecure flag

### ISSUE THREAD

**Issue by GarethCott** [Bartis1313/csgo#57]
I am having abit of an issue when injecting the dll. When I use the -insecure flag when lunching csgo the menu works and the hack runs perfect. When I remove the -insecure flag the menu doesn't appear and cheat doesn't work.

Is there some settings I am missing? Looked through the code and couldn't find anything about this.

**Comment by Bartis1313** [comment]
injector

**Comment by GarethCott** [comment]
I am using a basic load library injector that I coded and it doesn't work.

**Comment by Bartis1313** [comment]
closing with [this](https://blog.counter-strike.net/index.php/2020/07/30736/) note for reader
