### ISSUE TITLE
lazy_importer.hpp is missing

### ISSUE THREAD

**Issue by deathruned** [Bartis1313/csgo#59]
Error C1083 Cannot open include file: 'lazy_importer.hpp': No such file or directory (compiling source file)

**Comment by harshpreets63** [comment]
Install vcpkg (link is in repo readme itself) then open cmd in vcpkg folder then type vcpkg integrate install
Then compile

**Comment by Bartis1313** [comment]
@deathruned please follow the reply and always read README in any project before asking.
