### ISSUE TITLE
Compile on linux?

### ISSUE THREAD

**Issue by IgorDePaula** [Bartis1313/csgo#60]

**Comment by Bartis1313** [comment]
you would have to change a lot of stuff, a lot.
First the ABI will be different for linux, that means many SDK structs padding going to be different.
Second is replacing all window api related stuff to linux.
And last is again SDK, you can sometimes encounter something working only on windows, whereas linux doesn't support it :/

**Comment by IgorDePaula** [comment]
Thank you. I look for something for linux, I use linux. But all cheats for linux broken some time ago.
