### ISSUE TITLE
Spectator list paste 

### ISSUE THREAD

**Issue by harshpreets63** [Bartis1313/csgo#62]
i Tried porting (copy pasting ) spectator list code from Null Hooks, as most of the code placement looked identical to me.
Spectator list GUI is working find, but it is not detecting any spectators even after trying debugging it for 3-5 hrs.(I don't know how c++ works).
Can you try debugging it, please, once?

Code taken from https://github.com/NullHooks/NullHooks/blob/main/src/core/features/misc/spectator_list.cpp

my try
[spectator_list.zip](https://github.com/Bartis1313/csgo/files/10798673/spectator_list.zip)

**Comment by Bartis1313** [comment]
You don't need surface for that, you have ImGui optionality with much more functionalities, as a reference look how playerlist tables are done. For any effects as fading etc, you can do it once player spec state changes.
For time I can do own impl of this I really have no idea when, you can expect end of this month or so.

**Comment by harshpreets63** [comment]
It works finally <3
pros- works perfectly , hides if no one spectates us.
cons - looks  lil bit odd, cant move, shows our name while spectating others.

it does the job :)
![image](https://user-images.githubusercontent.com/19235185/220958686-3fbb2982-b9a3-48f2-9b2d-03700ac7d1ea.png)


[spectator_list.zip](https://github.com/Bartis1313/csgo/files/10815548/spectator_list.zip)

**Comment by Bartis1313** [comment]
Thanks, I will keep it as opened for some time. My plan is to add an imgui window, with horizontal dummies that act as a fully-width widget, on hover it shows some of the information we could possibly want to read: stats, steam image, steam info.
To add a nice effect you can adapt alpha change in color of the text when they disappear from the list / appear.
New commit will have such thing.

**Comment by Bartis1313** [comment]
done, my way differs a lot, in a good way.
About user info, I found it useless, and pics were too small to make any difference
