### ISSUE TITLE
got some errors 

### ISSUE THREAD

**Issue by krispyking24** [Bartis1313/csgo#64]
i got some errors when i tried compiling it in vs heres what the error is/showed im using the same methods i use to compile neps, nullhooks, orsiris idk what i done wrong if anything
[error log.txt](https://github.com/Bartis1313/csgo/files/10848646/error.log.txt)

**Comment by harshpreets63** [comment]
Install vcpkg 
Then integrate it with visual studio 
Using
Vcpkg install integrate (check vcpkg website for correct command)
Then enable vcpkg from solution properties
Then build

**Comment by krispyking24** [comment]
ok thank you for the fast reply its taking longer then before as now its downloading the other things like cmake and things which is good

**Comment by krispyking24** [comment]
got more errors in the end to cut to it it says 
"error C2039: 'call_once': is not a member of 'std'", " message : see declaration of 'std'", "error C3861: 'call_once': identifier not found"
[error.txt](https://github.com/Bartis1313/csgo/files/10849307/error.txt)

**Comment by harshpreets63** [comment]
> got more errors in the end to cut to it it says "error C2039: 'call_once': is not a member of 'std'", " message : see declaration of 'std'", "error C3861: 'call_once': identifier not found" [error.txt](https://github.com/Bartis1313/csgo/files/10849307/error.txt)

Try downloading source again and building
It works superb fine with vcpkg is installed

**Comment by krispyking24** [comment]
ok will try again tomorrow afternoon thanks again for the help

**Comment by krispyking24** [comment]
![image](https://user-images.githubusercontent.com/77263183/222145875-0ed59b85-3d30-4b09-9ad7-9b73c63382c8.png)
still errored heres the error list

**Comment by harshpreets63** [comment]
make sure CharacterSet MultiByte is Multibyte 
PlatformToolset is  v143
RuntimeLibrary is MultiThreaded

**Comment by krispyking24** [comment]
yeah it all is

**Comment by Bartis1313** [comment]
your linker didn't link mutex for those files.

**Comment by krispyking24** [comment]
so how would i fix that?

**Comment by Bartis1313** [comment]
include mutex header

**Comment by Bartis1313** [comment]
should never happen now, pull 2.0.2
