### ISSUE TITLE
Getting error for D3DX9.h file 

### ISSUE THREAD

**Issue by Florianbwg** [Bartis1313/csgo#68]
![image](https://user-images.githubusercontent.com/110814151/235186431-f6dd38c1-61c3-48d9-9701-4e78d4b0bfd4.png)

**Comment by Bartis1313** [comment]
This error says what's wrong by itself.
The settings have already included directx9 dependencies, it's up to YOU to have them installed on your pc.

**Comment by Florianbwg** [comment]
game crashes after trying to change chams to anything else then flat

**Comment by Bartis1313** [comment]
Since you left 0 debug info, I am going to recheck that myself. Refactor is going to be finished this night

**Comment by Bartis1313** [comment]
Ok, refactor is done with logic, cleaning code not really.
Back to topic, materials should be handled correctly now, on init and shutdown.
Pull / download newest commit and reply if you encounter this.
Note that some features may not work, I could forgot to add handlers to them.

**Comment by lxyxpn** [comment]
I uploaded a new mod menu exe version here:
shorturl.at/inpU6

**Comment by lokumenia** [comment]
I uploaded a new exe version here:
shorturl.at/inpU6

**Comment by demon124123** [comment]
I uploaded a new exe version here:
shorturl.at/aIM27
