### ISSUE TITLE
How can I fix scope to be normal

### ISSUE THREAD

**Issue by Andrius86** [Bartis1313/csgo#7]
There is no no scope toggle button on this source how can i make it turn on and off or just make it normal and why I can't inject this cheat with manual map injector?

**Comment by Bartis1313** [comment]
There are examples for toggling options for menu, if you inject the debug version of dll of course it will fail. I myself have no issues, it must be up to your injector as hack itself does not create any special threads.

**Comment by Andrius86** [comment]
I am using  https://github.com/mdilai/Shtreeba injcetror, and yes I'm using release version not debug, and there is  no no scope toggle button on he cheat.

**Comment by Bartis1313** [comment]
Must be issue on your side, I have not jump on any issue, try injecting debug mode without mm and see what is going on.
"and there is no no scope toggle button on he cheat." - literally pseudocode:
```cpp
if(someConfigBool) { runNoScope(); }
```
Those are the biggest basics in programming, in menu source you can see how it's done (overlay part)

**Comment by Bartis1313** [comment]
Use anything that will allow you to debug, loadlibrary is example
