### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by jbimbo321** [Bartis1313/csgo#75]
I am having issues with compiling this, the directions were not clear to me. Examples:

C1083: Cannot open include file: 'd3dx9.h': No such file or directory

error C2976: 'magic_enum::detail::names_v': too few template arguments (compiling source file hack\menu\GUI-ImGui\sections\misc\misc.cpp)

error C2062: type 'unknown-type' unexpected (compiling source file hack\menu\GUI-ImGui\sections\misc\misc.cpp)

error C3536: 'view_arr': cannot be used before it is initialized (compiling source file hack\menu\GUI-ImGui\sections\misc\misc.cpp)

error C2109: subscript requires array or pointer type (compiling source file hack\menu\GUI-ImGui\sections\misc\misc.cpp)

and a bunch of ImGui::MultiCombo errors.

**Comment by Bartis1313** [comment]
d3dx9.h - your own problem
magic_enum::detail::names_v - maybe something changed in lib and i got old lib bins in project
view_arr - something with sdd

Can you point which lines?

**Comment by jbimbo321** [comment]
View_arr error points to line 11 in prettyNames.hpp. Getting lots of errors in this file.

Idk what's going on with d3dx9.h or with all these errors tbh but I guess ill try again later.

**Comment by Bartis1313** [comment]
I have installed the most recent version of libraries, and their ABI changes (if any) did not cost me failing to compile.
Are you sure you have followed the building guide?
The dx error tells that you don't have installed dx SDK, which is also linked in readme.
Last thing, if you have old vs version, this might throw such errors.

**Comment by Glokk23** [comment]
i also have issues compiling related to line 11 in prettyNames.hpp here are a list of the errors

![Capture](https://github.com/Bartis1313/csgo/assets/71922108/45ac2268-35a5-44c1-a2df-7726f445b95b)

**Comment by Bartis1313** [comment]
retry now

**Comment by jbimbo321** [comment]
Yeah the d3dx9 error was on me, fixed with https://www.microsoft.com/en-us/download/details.aspx?id=6812.
Your fix works and now it compiles thank you.
