### ISSUE TITLE
The x88 menu font

### ISSUE THREAD

**Issue by Glokk23** [Bartis1313/csgo#76]
the x88 menu font is not the same as the one in the picture which is the original x88 font and the text is not outlined for me either, i couldn't find anywhere to change this in the menu

![image](https://github.com/Bartis1313/csgo/assets/71922108/2c9ca29d-83b1-45aa-9391-d6f8874e6e1a)

the pic above only has outlined text bc I added it in the code myself after but could not find what font he used

**Comment by Bartis1313** [comment]
The picture was taken months ago, and it was drawn with surface.
I dropped it because I was lazy to fix issues with making surface render to be streamproof.
In short, if you unlock surface rendering you can go back to pretty old commits and see how was it drawn.

**Comment by Bartis1313** [comment]
@Glokk23 I pushed version for macro choice

**Comment by Glokk23** [comment]
funnily enough i didn't see this and made my own solution, 

// Replace the existing drawText function in x88menu.cpp
#if ORIGINAL_DRAW == true
static void drawText(float x, float y, unsigned long font, const std::string& text, const Color& color)
{
    SurfaceRender::text(static_cast<int>(x), static_cast<int>(y), font, text, false, color);
}
#else
static void drawText(float x, float y, ImFont* font, const std::string& text, const Color& color)
{
    surfaceRender.text(static_cast<int>(x), static_cast<int>(y), font, text, false, color);
}
#endif
