### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by chapparron** [Bartis1313/csgo#77]
yo, my game is crashing on injection, but why?

**Comment by Bartis1313** [comment]
maybe debug?

**Comment by chapparron** [comment]
aslo crashing

**Comment by Bartis1313** [comment]
I am telling you to debug it, of course debug version is also required for that

**Comment by chapparron** [comment]
okay I will test it after my game

**Comment by chapparron** [comment]
builded on debug x86 and injected with AlisInjector(x86). An Console opened and it crashed after 10 sec

**Comment by Bartis1313** [comment]
So that's how you debug the app? Just by injecting it? Please attach debugger, and then post the information.

**Comment by chapparron** [comment]
wich debugger should I use?

**Comment by chapparron** [comment]
if it says "interfaces sucsess" my game crashes

**Comment by Bartis1313** [comment]
... you are able to compile and not debug?

**Comment by Bartis1313** [comment]
click debug tab in visual studio, then click attach to, select csgo and see where does it crash.

**Comment by chapparron** [comment]
I am getting an Messagebox in Visual studio then: Exception thrown at 0x3BBBCBED in csgo.exe: 0xC0000005: Access violation reading location 0x00000004.

**Comment by Bartis1313** [comment]
screen it, where does it say so

**Comment by chapparron** [comment]
after it says interfaces success: 
![image](https://github.com/Bartis1313/csgo/assets/122289288/94173ef9-5a13-4644-83fd-e1f33f0f2b01)

**Comment by Bartis1313** [comment]
Are you sure you are up to date? If crash happens it points to nowhere (see stack output)? After interfaces there is a memory init, so this is the place where you experience that most likely.

**Comment by chapparron** [comment]
yes, I downloaded the newest Version

**Comment by Bartis1313** [comment]
OK, there won't be any stack. Anyway here is what has passed for you: [this](https://github.com/Bartis1313/csgo/blob/master/hack/gamememory/memory.cpp#L185)
and couldn't go to this: [here](https://github.com/Bartis1313/csgo/blob/master/hack/gamememory/memory.cpp#L206)
Which is not possible, all there addresses are valid for latest binaries. Maybe while you inject, imports get invalid anyhow. Try loading up with simple injector like extreme injector and go with default settings. Of course for safety add insecure flag, because that will get you banned obviously.

**Comment by Bartis1313** [comment]
AH and, did you debug with manual map? That for sure won't work

**Comment by Bartis1313** [comment]
Read up how manual mapping works then, that thing won't let you debug that easily. And also, crash could have many reasons, maybe exceptions are not handled, maybe imports are not handled. You would have to go to that address and look what has been accessed and what failed, manually.

**Comment by chapparron** [comment]
I injected with an simple self coded load libary injector and it works :), Ty for the Help

**Comment by Bartis1313** [comment]
Next time I suggest making own "injector" and understand what's going on. There is not a must to ensure your safety by just manual map, there are many other good ways too. And read what the imports do, part of PE header.
Thank you.

**Comment by Bartis1313** [comment]
@chapparron sorry for bump. Expect update which fixes issues with manual map, I restricted exceptions. You will be to control the flow with simple one macro.

**Comment by Bartis1313** [comment]
fixed
