### ISSUE TITLE
Errors when building in release but not in debug

### ISSUE THREAD

**Issue by DemonLoverHvH** [Bartis1313/csgo#9]
as the title says im only getting error when building in release
![68a0800f9272ce6bbddd369141f706b7](https://user-images.githubusercontent.com/51270049/147709175-27da7e23-d511-4ebd-b455-63b9e126706f.png)

**Comment by Bartis1313** [comment]
Thanks for reporting the issue. It was the problem that as default lazy importer constructor behaves as get() method in it, in this case it could lead to many undefines and such. Fixed now

**Comment by DemonLoverHvH** [comment]
> 
ok thanks<3

**Comment by Bartis1313** [comment]
> also do you have a discord I could add so if i stumble on some small problems i could just shoot you a messages instead of making a thread

Yes I do own a discord account, I prefer reporting issues here instead of pm'ing me. Bartis#3611
